### ISSUE TITLE
Add helper methods

### ISSUE THREAD

**Issue by eluce2** [proofgeist/fmdapi#1]
Ideas:
`findOne` should return a single object and throw error if 0 or more than 1 record are found
`findFirst` should return a single object but not throw if more than 1 record found
`listAll` should automatically list all records from a table, handle paging (use with caution!)
`findAll` handle paging for a find (use with caution!)
`updateById` should allow updating a record by a defined primary key instead of record id (would use `findOne` under the hood)

**Comment by toddgeist** [comment]
these are good.  

I have often thought about adding updateById feature to Otto's proxy.  That way the second request wouldn't even leave the server.  I Never could decide on the right API though.

 But I think it is worth doing with the client.  If we ever added it otto the client could use that instead

**Comment by eluce2** [comment]
`findAll` and `listAll` have been added in v.1.1.0

**Comment by eluce2** [comment]
Closing this issue for now, we may come back to the `updateById` method at a later time, but the rest have already been implemented
