### ISSUE TITLE
Should `findAll` support the `ignoreEmptyResult` flag?

### ISSUE THREAD

**Issue by theandychase** [proofgeist/fmdapi#11]
I'll submit a PR if it makes sense

**Comment by eluce2** [comment]
Yes, it should. I thought it did already as the arguments of `findAll` just pass through to the `find` function, so it could simply be a missing type issue

**Comment by eluce2** [comment]
This was actually changed with a recent upgrade. the `ignoreEmptyResult` flag is intentionally removed from that method because it's now forced to `true` by default.
