### ISSUE TITLE
Missing docs on how to get started with codegen.

### ISSUE THREAD

**Issue by erikfunkis** [proofgeist/fmdapi#136]
Hi!

I'm working on a relatively big Filemaker solution (50-100 tables with lots of data) that we would like to eventually migrate to a pure Typescript solution. I stumbled across this library and think it looks very useful to begin that process. 
Especially, I love the prospect of generating Zod-schemas or at least TS types from inspecting the database.

The docs mention "automatic type generation" (or try to link to a section named accordingly [like this one](https://github.com/proofgeist/fmdapi?tab=readme-ov-file#automatic-type-generation)) , but I can't seem to follow those links. Is this info available elsewhere? 

Ps. If you have any suggestions about how you would approach the problem differently I would gladly take them. I'm thinking a Typescript integration with the database will be good first step for us to move some of the functionality from Filemaker by talking directly to the database through Typescript rather than to try to use the Filemaker built-in Rest api features and similar. 

If you or any of the library maintainers do consulting work then that could also be on the table. 

Thanks for great resources (other Filemaker related libs) by the way. You seem to know your way around the Filemaker eco-system.

**Edit**:  Never mind about the docs. I found them in the wiki which I did a free-text search in and failed to find anything, but I see now I missed the sidebar sections.. 🤦

**Comment by eluce2** [comment]
Glad we could help! Yes, we also do consulting work and these libraries are a result of our experience with lots and lots of FileMaker projects. You can learn more and contact our consulting team at proofgeist.com.

I will also update the readme to better link to that Wiki Page that is referenced
