### ISSUE TITLE
Codegen: Schema names ending with a number are handled inconsistently

### ISSUE THREAD

**Issue by erikfunkis** [proofgeist/fmdapi#140]
For example, with a `fmschema.config.mjs` containing a schemas entry like  
```javascript
{
    "layout": "Name2",
    "schemaName": "Name2"
 }
```

That would generate correct file names (with the number, 2 in this case) included.  But within the schema file  `Name2.ts` we would get schemas like 

```javascript
// note "2" is gone here.
export const ZName = z.object({
// correct stuff  here
})

// note "2" is gone here.
export type TName = z.infer<typeof ZName>;
```

and then in the generated Client file `client/Name2.ts` there would be a mix of the name with and without the number.

like

```javascript
// imports correctly using names including "2", but since the 2 is missing in the schema above they fail.
import { TName2, ZName2 } from "../Name2";

// Then later here  the name is without the "2" again

export const client = DataApi<any, TName>({ 

// again without the "2"
zodValidators: { fieldData: ZName }
})
```

Best of luck, and thanks for the great lib!

**Comment by eluce2** [comment]
Should be fixed in 4.0.1!
