### ISSUE TITLE
Getting 'Exceeded host's capacity' from filemaker and seeing lots of POSTs to sessions

### ISSUE THREAD

**Issue by mjs2020** [proofgeist/fmdapi#18]
Disclaimer: I'm integrating something with a filemaker instance that someone else manages. I have JS/TS knowledge but not much Filemaker experience.

I'm writing a piece of software, running in ts-node that reads messages from a queue, does some processing and is supposed to post a result to filemaker. I've tried integrating `@proofgeist/fmdapi` and the app runs for a while and then starts receiving `Exceeded host's capacity` errors back from FM.

The FM server admin showed me some logs like the following (project-specific details hidden):
```
...
2023-04-21 14:04:10.944 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout1/records	84
2023-04-21 14:04:12.283 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	118
2023-04-21 14:04:12.325 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout2/records	84
2023-04-21 14:04:12.468 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	117
2023-04-21 14:04:12.483 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout1/records	84
2023-04-21 14:04:13.955 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	117
2023-04-21 14:04:13.998 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout3/records	84
2023-04-21 14:04:14.249 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	118
2023-04-21 14:04:14.283 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout2/records	84
2023-04-21 14:04:14.407 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	116
2023-04-21 14:04:14.423 +0000	0	INFO	172.xxx.xxx.xxx	api.user	POST	/fmi/data/vLatest/databases/PROJECT_main/layouts/Layout1/records	84
2023-04-21 14:04:15.487 +0000	812	ERROR	172.xxx.xxx.xxx		POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	80
2023-04-21 14:04:15.610 +0000	812	ERROR	172.xxx.xxx.xxx		POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	80
2023-04-21 14:04:15.657 +0000	812	ERROR	172.xxx.xxx.xxx		POST	/fmi/data/vLatest/databases/PROJECT_main/sessions	80
```

It looks as if a POST to /sessions is made before each request and after a while this starts failing. Is this expected?
The admin has tried increasing the ProConnections setting from 250 to 500 but we still get failures.

In my code I'm caching and not re-creating the client:
```
// in a class that is only instantiated once and reused across messages:
this.fmClient = DataApi({
  auth: { username: this.FM_USER, password: this.FM_PASS },
  db: this.FM_DB,
  server: this.FM_API_URL,
})

// then used:
abstract class FmRecord {
  public abstract layout: string
  public abstract fieldData: Object
}

export async function insertFilemakerRecord({ layout, fieldData }: FmRecord) {
  try {
    await otherClassInstance.fmClient.create({ layout, fieldData })
  } catch (e) {
    logger.error(`Failed to insert record into ${layout}, data was: ${JSON.stringify(fieldData, null, 2)}`)
    throw e
  }
}
```

**Comment by eluce2** [comment]
When you connect to a FileMaker server via username and password, an access token must be created. The library attempts to reuse this access token for you, but it's not always possible depending on how your node code is running. If you're running with NODE_ENV as `development`, then there will be a `shared.json` file with this access token. Otherwise the token it only stored in memory and will only be re-used if the same process calls the API again.

One way around this is to use the [Otto Data API proxy](https://www.ottofms.com/docs/otto/working-with-otto/proxy-api-keys/data-api). Otto lets you create a expiring API key for all your requests and then manages the sessions locally on the FileMaker server. I believe this feature of Otto is available even without an Otto license, but it does require you to install Otto on the FileMaker Server.

Since you mentioned that you don't have direct access to the FM server, another thing you might be able to try is call the `disconnect` method on the provided client. This will still cause the `/session` endpoint to be called on each request, but it would ensure the no lone sessions are left active on the server, which will avoid the error you're seeing.

Let me know if this helps!

**Comment by mjs2020** [comment]
Thanks @eluce2 that was very helpful. In fact I should have just looked at the code.
Also thanks for this very usefil library (sorry I should have opened with that previously 😄)

In my use case I plan to have multiple workers running on the same machine so using shared.json between them makes a lot of sense. Seems like a production feature to me though, not something dependent on `NODE_ENV==='development'`. Perhaps an option to `DataApi()`?

> Otherwise the token it only stored in memory and will only be re-used if the same process calls the API again.

I don't think this is true and was the cause of my issue. Should be simple to fix, would be happy to work on a PR sometime next week.

**Comment by eluce2** [comment]
Actually, I'm just on the verge of releaseing v3 which will give you control over where the access token is stored. Check out my v3 branch if you want to give any feedback or testing before I release next week

**Comment by eluce2** [comment]
I know it may seem like a strange choice to limit the .json file method to `NODE_ENV==='development'`, but the primary use case we had in mind for this library was running on serverless functions where we don't have full access to the file system, and we try to use the Otto API key method whenever possible. We would have kept it all in memory, but when you restart your dev server so frequently during development, a new token each time would overwhelm the server (like the issue you ran into)

I am curious about your setup though—are you using a long-running node process like express in production? I'd welcome other suggestions or contributions.

**Comment by mjs2020** [comment]
Yes, I've got a long running process with an AWS SQS consumer. I've got jobs that get posted to the queue and the consumer runs them and publishes the results to FM. I'm planning to scale the workers horizontally but the token in `shared.json` is stored in an EFS mount so the whole fleet of workers I may want to create can use the same shared token now.

**Comment by toddgeist** [comment]
Here are some things you may want to consider.

- A token equals a session. A session is single-threaded. Requests in a single session will just queue up.
- If you use different tokens, you can get different sessions. Each session will run on its own thread. You get some concurrency this way
- However, if you let every connection create a new session and you don't disconnect each time, you overwhelm the server's available connections, as you have seen.

So you may want to limit the number of workers. Or use a connection pool of tokens.  Or just disconnect after each connection.

I know you said you don't control the server. But we built tools for precisely this kind of scenario with FileMaker. One of the tools is not free, but the other is. Both would need to be installed on the server. Let us know if you or your FileMaker server admin would like to know more.

All the best.

Todd

**Comment by mjs2020** [comment]
Thanks very much for the heads-up! Much appreciated. I will point the admin in your direction.
