### ISSUE TITLE
using find - omit doesn't match types

### ISSUE THREAD

**Issue by anthony-healthstreet** [proofgeist/fmdapi#22]
Using the `find` function, adding the `omit` key causes a type error when setting to anything other than undefined

![image](https://user-images.githubusercontent.com/96539866/234918078-45f304a9-c193-4145-b7d7-59f87058421e.png)
![image](https://user-images.githubusercontent.com/96539866/234918103-02547758-b5ad-4d6a-bac1-97d1dda14886.png)
![image](https://user-images.githubusercontent.com/96539866/234918382-583ef458-0033-45ef-ae7d-629077ef6ed9.png)
![image](https://user-images.githubusercontent.com/96539866/234918297-33d96f48-6b04-4704-86f6-c39171903592.png)

**Comment by eluce2** [comment]
I was able to replicate this issue but it only occurs when you are not passing types to either the client or the find method. I highly suggest using the [codegen tool](https://github.com/proofgeist/fmdapi#automatic-type-generation) to generate the client, but you can fix this type error manually be specifying which fields are expected to be on that layout.

At the find method level:
```ts
client.find<{ test: string; }>({ query: { test: "test", omit: true } })
```

At the client level:
```ts
const client = DataApi<any, { test: string; }>({
    ...
})
```
