### ISSUE TITLE
Include `main` export definitions

### ISSUE THREAD

**Issue by alexandrosraikos** [proofgeist/fmdapi#94]
I am locked still back in version 3.2.2, because ever since `exports` were defined in `package.json` my Gatsby & Netlify functions build breaks. Please fix the imports so both my bundler and my IDE correctly identify the module.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main

**Comment by eluce2** [comment]
Could you provide more info about the build error you are seeing? Are you using CommonJS or the require syntax for example?
