### ISSUE TITLE
`_sort` parameter not correctly converted

### ISSUE THREAD

**Issue by alexandrosraikos** [proofgeist/fmdapi#95]
When using `list` or `listAll`, the `sort` property doesn't get converted to a `URLSearchParams` string correctly. This is the faulty output right before making the request:

```typescript
URLSearchParams { '_limit' => '15', '_sort' => '[object Object]' }
```

I have to ignore the typescript warnings for the `sort` property when defining it and directly create the string instead, thus it correctly performs the request as:

```typescript
URLSearchParams {
  '_limit' => '15',
  '_sort' => '[{ "fieldName": "Short_Title", "sortOrder": "ascend" }]'
}
```

**Comment by eluce2** [comment]
I believe this was fixed in a recent version. Which version are you seeing this behavior?
